import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from '../components/Header'
import Statistics from "../components/Statistics";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="Dashboard"/>
      
      <main className={styles.main}>
        <h1>Main body</h1>
        <div>
          <ul>
            <li>
              <p>369876987</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
            <li>
              <p>34</p>
            </li>
          </ul>
        </div>
        <Statistics />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
